### ISSUE TITLE
Functions

### ISSUE THREAD

**Issue by v0idpwn** [lambda-study-group/lambdinha-bot#1]
What functions should lambdinha have for a minimum viable product?

**Comment by v0idpwn** [comment]
- /challenge: post a brief description of the current challenge with a link for more information
- /ranking: post current ranking from the challenges repo
- /prs: post current open prs in the challenges repo, so people can be aware when there are new prs to analyze and improve, getting them more points

**Comment by anabastos** [comment]
@v0idpwn 
Nice functionalities that I think that should be included:
- **/welcome:** Welcome message when someone joins the group explaning the purpose of the group(including links to our repositories) and asking the person to introduce herself
- **/joke:** Telling fp jokes randomly
- **/ban PERSONNAME** Ban solicitation

**Comment by ihavenonickname** [comment]
`/monad`: Replies "A monad is just a monoid in the category of endofunctors"

**Comment by anabastos** [comment]
@ihavenonickname Awesome
