### ISSUE TITLE
create a rest endpoint to jokes

### ISSUE THREAD

**Issue by souenzzo** [lambda-study-group/lambdinha-bot#10]
create a rest endpoint like `/joikes` that returns `{"joke": "..."}`
Then I will add that random joke on http://lambda-study-group.github.io/

**Comment by v0idpwn** [comment]
isn't it better to do a request to https://raw.githubusercontent.com/lambda-study-group/lambdinha-bot/master/jokes.json and select a random joke from the output? similarly to what we do on 
```elixir

  def get_joke(number \\ "") do
    HTTPoison.get("https://raw.githubusercontent.com/lambda-study-group/lambdinha-bot/master/jokes.json")
    |> handle_response
    |> extract_joke(number)
  end
  
  def extract_joke(map, _number="") do
    {:ok, body} = map
    item = Enum.random body
    '#{item["joke"]}'
  end
```

**Comment by souenzzo** [comment]
Nice! I will do it!

**Comment by v0idpwn** [comment]
github has a better uptime than lambdinha :yum:
